// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/office.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type OfficeService int32

const (
	OfficeService_OFFICES OfficeService = 0
)

var OfficeService_name = map[int32]string{
	0: "OFFICES",
}

var OfficeService_value = map[string]int32{
	"OFFICES": 0,
}

func (x OfficeService) String() string {
	return proto.EnumName(OfficeService_name, int32(x))
}

func (OfficeService) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_fbd6dc5308f220a6, []int{0}
}

type OfficeEvents int32

const (
	OfficeEvents_CREATE_OFFICE  OfficeEvents = 0
	OfficeEvents_OFFICE_CREATED OfficeEvents = 1
	OfficeEvents_UPDATE_OFFICE  OfficeEvents = 2
	OfficeEvents_OFFICE_UPDATED OfficeEvents = 3
	OfficeEvents_DELETE_OFFICE  OfficeEvents = 4
	OfficeEvents_OFFICE_DELETED OfficeEvents = 5
)

var OfficeEvents_name = map[int32]string{
	0: "CREATE_OFFICE",
	1: "OFFICE_CREATED",
	2: "UPDATE_OFFICE",
	3: "OFFICE_UPDATED",
	4: "DELETE_OFFICE",
	5: "OFFICE_DELETED",
}

var OfficeEvents_value = map[string]int32{
	"CREATE_OFFICE":  0,
	"OFFICE_CREATED": 1,
	"UPDATE_OFFICE":  2,
	"OFFICE_UPDATED": 3,
	"DELETE_OFFICE":  4,
	"OFFICE_DELETED": 5,
}

func (x OfficeEvents) String() string {
	return proto.EnumName(OfficeEvents_name, int32(x))
}

func (OfficeEvents) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_fbd6dc5308f220a6, []int{1}
}

type Office struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Address              *Address `protobuf:"bytes,3,opt,name=Address,proto3" json:"Address,omitempty"`
	AddressID            string   `protobuf:"bytes,4,opt,name=AddressID,proto3" json:"AddressID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Office) Reset()         { *m = Office{} }
func (m *Office) String() string { return proto.CompactTextString(m) }
func (*Office) ProtoMessage()    {}
func (*Office) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbd6dc5308f220a6, []int{0}
}

func (m *Office) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Office.Unmarshal(m, b)
}
func (m *Office) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Office.Marshal(b, m, deterministic)
}
func (m *Office) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Office.Merge(m, src)
}
func (m *Office) XXX_Size() int {
	return xxx_messageInfo_Office.Size(m)
}
func (m *Office) XXX_DiscardUnknown() {
	xxx_messageInfo_Office.DiscardUnknown(m)
}

var xxx_messageInfo_Office proto.InternalMessageInfo

func (m *Office) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Office) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Office) GetAddress() *Address {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *Office) GetAddressID() string {
	if m != nil {
		return m.AddressID
	}
	return ""
}

type Address struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	RoadName             string   `protobuf:"bytes,2,opt,name=RoadName,proto3" json:"RoadName,omitempty"`
	Number               int32    `protobuf:"varint,3,opt,name=Number,proto3" json:"Number,omitempty"`
	ZipCode              int32    `protobuf:"varint,4,opt,name=ZipCode,proto3" json:"ZipCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Address) Reset()         { *m = Address{} }
func (m *Address) String() string { return proto.CompactTextString(m) }
func (*Address) ProtoMessage()    {}
func (*Address) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbd6dc5308f220a6, []int{1}
}

func (m *Address) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Address.Unmarshal(m, b)
}
func (m *Address) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Address.Marshal(b, m, deterministic)
}
func (m *Address) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Address.Merge(m, src)
}
func (m *Address) XXX_Size() int {
	return xxx_messageInfo_Address.Size(m)
}
func (m *Address) XXX_DiscardUnknown() {
	xxx_messageInfo_Address.DiscardUnknown(m)
}

var xxx_messageInfo_Address proto.InternalMessageInfo

func (m *Address) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Address) GetRoadName() string {
	if m != nil {
		return m.RoadName
	}
	return ""
}

func (m *Address) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *Address) GetZipCode() int32 {
	if m != nil {
		return m.ZipCode
	}
	return 0
}

type CreateOffice struct {
	Office               *Office  `protobuf:"bytes,1,opt,name=Office,proto3" json:"Office,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateOffice) Reset()         { *m = CreateOffice{} }
func (m *CreateOffice) String() string { return proto.CompactTextString(m) }
func (*CreateOffice) ProtoMessage()    {}
func (*CreateOffice) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbd6dc5308f220a6, []int{2}
}

func (m *CreateOffice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOffice.Unmarshal(m, b)
}
func (m *CreateOffice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOffice.Marshal(b, m, deterministic)
}
func (m *CreateOffice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOffice.Merge(m, src)
}
func (m *CreateOffice) XXX_Size() int {
	return xxx_messageInfo_CreateOffice.Size(m)
}
func (m *CreateOffice) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOffice.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOffice proto.InternalMessageInfo

func (m *CreateOffice) GetOffice() *Office {
	if m != nil {
		return m.Office
	}
	return nil
}

type OfficeCreated struct {
	Office               *Office  `protobuf:"bytes,1,opt,name=Office,proto3" json:"Office,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OfficeCreated) Reset()         { *m = OfficeCreated{} }
func (m *OfficeCreated) String() string { return proto.CompactTextString(m) }
func (*OfficeCreated) ProtoMessage()    {}
func (*OfficeCreated) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbd6dc5308f220a6, []int{3}
}

func (m *OfficeCreated) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OfficeCreated.Unmarshal(m, b)
}
func (m *OfficeCreated) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OfficeCreated.Marshal(b, m, deterministic)
}
func (m *OfficeCreated) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OfficeCreated.Merge(m, src)
}
func (m *OfficeCreated) XXX_Size() int {
	return xxx_messageInfo_OfficeCreated.Size(m)
}
func (m *OfficeCreated) XXX_DiscardUnknown() {
	xxx_messageInfo_OfficeCreated.DiscardUnknown(m)
}

var xxx_messageInfo_OfficeCreated proto.InternalMessageInfo

func (m *OfficeCreated) GetOffice() *Office {
	if m != nil {
		return m.Office
	}
	return nil
}

type OfficeUpdated struct {
	Office               *Office  `protobuf:"bytes,1,opt,name=Office,proto3" json:"Office,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OfficeUpdated) Reset()         { *m = OfficeUpdated{} }
func (m *OfficeUpdated) String() string { return proto.CompactTextString(m) }
func (*OfficeUpdated) ProtoMessage()    {}
func (*OfficeUpdated) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbd6dc5308f220a6, []int{4}
}

func (m *OfficeUpdated) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OfficeUpdated.Unmarshal(m, b)
}
func (m *OfficeUpdated) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OfficeUpdated.Marshal(b, m, deterministic)
}
func (m *OfficeUpdated) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OfficeUpdated.Merge(m, src)
}
func (m *OfficeUpdated) XXX_Size() int {
	return xxx_messageInfo_OfficeUpdated.Size(m)
}
func (m *OfficeUpdated) XXX_DiscardUnknown() {
	xxx_messageInfo_OfficeUpdated.DiscardUnknown(m)
}

var xxx_messageInfo_OfficeUpdated proto.InternalMessageInfo

func (m *OfficeUpdated) GetOffice() *Office {
	if m != nil {
		return m.Office
	}
	return nil
}

type UpdateOffice struct {
	Office               *Office  `protobuf:"bytes,1,opt,name=Office,proto3" json:"Office,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateOffice) Reset()         { *m = UpdateOffice{} }
func (m *UpdateOffice) String() string { return proto.CompactTextString(m) }
func (*UpdateOffice) ProtoMessage()    {}
func (*UpdateOffice) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbd6dc5308f220a6, []int{5}
}

func (m *UpdateOffice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateOffice.Unmarshal(m, b)
}
func (m *UpdateOffice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateOffice.Marshal(b, m, deterministic)
}
func (m *UpdateOffice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateOffice.Merge(m, src)
}
func (m *UpdateOffice) XXX_Size() int {
	return xxx_messageInfo_UpdateOffice.Size(m)
}
func (m *UpdateOffice) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateOffice.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateOffice proto.InternalMessageInfo

func (m *UpdateOffice) GetOffice() *Office {
	if m != nil {
		return m.Office
	}
	return nil
}

type DeleteOffice struct {
	Office               *Office  `protobuf:"bytes,1,opt,name=Office,proto3" json:"Office,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteOffice) Reset()         { *m = DeleteOffice{} }
func (m *DeleteOffice) String() string { return proto.CompactTextString(m) }
func (*DeleteOffice) ProtoMessage()    {}
func (*DeleteOffice) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbd6dc5308f220a6, []int{6}
}

func (m *DeleteOffice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteOffice.Unmarshal(m, b)
}
func (m *DeleteOffice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteOffice.Marshal(b, m, deterministic)
}
func (m *DeleteOffice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteOffice.Merge(m, src)
}
func (m *DeleteOffice) XXX_Size() int {
	return xxx_messageInfo_DeleteOffice.Size(m)
}
func (m *DeleteOffice) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteOffice.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteOffice proto.InternalMessageInfo

func (m *DeleteOffice) GetOffice() *Office {
	if m != nil {
		return m.Office
	}
	return nil
}

type OfficeDeleted struct {
	Office               *Office  `protobuf:"bytes,1,opt,name=Office,proto3" json:"Office,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OfficeDeleted) Reset()         { *m = OfficeDeleted{} }
func (m *OfficeDeleted) String() string { return proto.CompactTextString(m) }
func (*OfficeDeleted) ProtoMessage()    {}
func (*OfficeDeleted) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbd6dc5308f220a6, []int{7}
}

func (m *OfficeDeleted) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OfficeDeleted.Unmarshal(m, b)
}
func (m *OfficeDeleted) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OfficeDeleted.Marshal(b, m, deterministic)
}
func (m *OfficeDeleted) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OfficeDeleted.Merge(m, src)
}
func (m *OfficeDeleted) XXX_Size() int {
	return xxx_messageInfo_OfficeDeleted.Size(m)
}
func (m *OfficeDeleted) XXX_DiscardUnknown() {
	xxx_messageInfo_OfficeDeleted.DiscardUnknown(m)
}

var xxx_messageInfo_OfficeDeleted proto.InternalMessageInfo

func (m *OfficeDeleted) GetOffice() *Office {
	if m != nil {
		return m.Office
	}
	return nil
}

func init() {
	proto.RegisterEnum("proto.OfficeService", OfficeService_name, OfficeService_value)
	proto.RegisterEnum("proto.OfficeEvents", OfficeEvents_name, OfficeEvents_value)
	proto.RegisterType((*Office)(nil), "proto.Office")
	proto.RegisterType((*Address)(nil), "proto.Address")
	proto.RegisterType((*CreateOffice)(nil), "proto.CreateOffice")
	proto.RegisterType((*OfficeCreated)(nil), "proto.OfficeCreated")
	proto.RegisterType((*OfficeUpdated)(nil), "proto.OfficeUpdated")
	proto.RegisterType((*UpdateOffice)(nil), "proto.UpdateOffice")
	proto.RegisterType((*DeleteOffice)(nil), "proto.DeleteOffice")
	proto.RegisterType((*OfficeDeleted)(nil), "proto.OfficeDeleted")
}

func init() { proto.RegisterFile("proto/office.proto", fileDescriptor_fbd6dc5308f220a6) }

var fileDescriptor_fbd6dc5308f220a6 = []byte{
	// 322 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x4f, 0x4d, 0x6b, 0xc2, 0x40,
	0x10, 0x35, 0xd1, 0x68, 0x1d, 0xa3, 0xa4, 0x73, 0x28, 0xa1, 0x78, 0x90, 0x40, 0x41, 0x3c, 0x58,
	0xb0, 0xd8, 0xbb, 0x64, 0x57, 0x08, 0x14, 0x2d, 0x6b, 0xbd, 0xf4, 0x22, 0xda, 0x5d, 0x8b, 0x50,
	0x1b, 0x89, 0xa9, 0x7f, 0xa0, 0x7f, 0xbc, 0x64, 0x67, 0xa3, 0x81, 0x5e, 0x9a, 0x9e, 0x76, 0xe6,
	0x7d, 0xec, 0x7b, 0x03, 0x78, 0x48, 0xe2, 0x34, 0xbe, 0x8f, 0xb7, 0xdb, 0xdd, 0x9b, 0x1a, 0xea,
	0x05, 0x1d, 0xfd, 0x04, 0x29, 0xd4, 0xe7, 0x1a, 0xc6, 0x0e, 0xd8, 0x11, 0xf3, 0xad, 0x9e, 0xd5,
	0x6f, 0x0a, 0x3b, 0x62, 0x88, 0x50, 0x9b, 0xad, 0xf7, 0xca, 0xb7, 0x35, 0xa2, 0x67, 0xec, 0x43,
	0x63, 0x22, 0x65, 0xa2, 0x8e, 0x47, 0xbf, 0xda, 0xb3, 0xfa, 0xad, 0x51, 0x87, 0x7e, 0x1b, 0x1a,
	0x54, 0xe4, 0x34, 0x76, 0xa1, 0x69, 0xc6, 0x88, 0xf9, 0x35, 0xfd, 0xc5, 0x05, 0x08, 0xde, 0xcf,
	0xff, 0xfc, 0x8a, 0xbd, 0x85, 0x2b, 0x11, 0xaf, 0x65, 0x21, 0xfa, 0xbc, 0xe3, 0x0d, 0xd4, 0x67,
	0x5f, 0xfb, 0x8d, 0x4a, 0x74, 0xba, 0x23, 0xcc, 0x86, 0x3e, 0x34, 0x5e, 0x77, 0x87, 0x30, 0x96,
	0x4a, 0x47, 0x39, 0x22, 0x5f, 0x83, 0x31, 0xb8, 0x61, 0xa2, 0xd6, 0xa9, 0x32, 0x47, 0xde, 0xe5,
	0xe7, 0xea, 0xc4, 0xd6, 0xa8, 0x6d, 0xfa, 0x13, 0x28, 0x0c, 0x19, 0x3c, 0x42, 0x9b, 0x26, 0x32,
	0xcb, 0xd2, 0xbe, 0xe5, 0x41, 0x96, 0xf1, 0x8d, 0xc1, 0x25, 0x47, 0xb9, 0x9a, 0x63, 0x70, 0x99,
	0xfa, 0x50, 0xff, 0xbe, 0x8e, 0xcc, 0x7f, 0x6d, 0x39, 0xe8, 0xe6, 0xbe, 0x85, 0x4a, 0x4e, 0x59,
	0x5e, 0x0b, 0x1a, 0xf3, 0xe9, 0x34, 0x0a, 0xf9, 0xc2, 0xab, 0x0c, 0xbe, 0x2d, 0x70, 0x89, 0xe6,
	0x27, 0xf5, 0x99, 0x1e, 0xf1, 0x1a, 0xda, 0xa1, 0xe0, 0x93, 0x17, 0xbe, 0x22, 0x91, 0x57, 0x41,
	0x84, 0x0e, 0xcd, 0x2b, 0x62, 0x98, 0x67, 0x65, 0xb2, 0xe5, 0x33, 0x2b, 0xc8, 0xec, 0x82, 0x8c,
	0x18, 0xe6, 0x55, 0x33, 0x19, 0xe3, 0x4f, 0xfc, 0x22, 0xab, 0x15, 0x64, 0xc4, 0x30, 0xcf, 0xd9,
	0xd4, 0x75, 0xf3, 0x87, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x77, 0xa4, 0xf3, 0xc2, 0xf3, 0x02,
	0x00, 0x00,
}
